sudo: false
language: perl
perl:
   - '5.12'
   - '5.14'
   - '5.16'
   - '5.18'
   - '5.20'
   - '5.22'
env: AUTHOR_TESTING=1 RELEASE_TESTING=1
matrix:
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest --skip-satisfied Pod::Elemental::Transformer::List
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - dzil authordeps --missing | cpanm --quiet --notest
script:
   - git checkout -b travis_build
   - dzil build
   - cd Compress-LZ4Frame-0.009 && ls -lA && perl Makefile.pl && make && perl -Mlib=lib -Mblib=blib travis-test.pl
