---
abstract: 'Compression package using the lz4frame library'
author:
  - 'Felix Bytow <felix.bytow@autinity.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compress-LZ4Frame
version: '0.006'
