---
abstract: 'Compression package using the lz4frame library'
author:
  - 'Felix Bytow <felix.bytow@autinity.de>'
build_requires:
  Test::More: '0'
  constant: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Compress-LZ4Frame
requires:
  Exporter: '0'
  XSLoader: '0'
  base: '0'
  perl: 5.010_001
  strict: '0'
  vars: '0'
  warnings: '0'
version: 0.001_001
